### ISSUE TITLE
No possible to login with google account

### ISSUE THREAD

**Issue by Wulfgardodin** [MaVeN-LLC/RVX#10]
In the rvx manager all Youtube Versions are not possible to log in with the google account. Also this Version on GitHub. It tells me proofe your Networkconnection. Before I installed new YouTube do not load Videos. All black and loading, loading, loading. I think Youtube cutted the connection. There are a new Version on playstore. It is very higher. Hope you can resolve the problem. Your make a very good job and thanks for it.
![Screenshot_20240909_213244_RVX](https://github.com/user-attachments/assets/927543e8-2218-4e80-ad15-d62734032c3e)

**Comment by TBNRDev** [comment]
https://github.com/MaVeN-LLC/RVX/releases/tag/v19.21.40
