### ISSUE TITLE
No full screen button

### ISSUE THREAD

**Issue by WWH-exe** [MaVeN-LLC/RVX#2]
The full screen button is not appearing on the corner of video player

Using Galaxy note 9 with android 10

**Comment by Bouab-Ahmed** [comment]
Facing the same probelm
Using Redmi note 8

**Comment by TBNRDev** [comment]
did you guys use the patch.txt

**Comment by WWH-exe** [comment]
Yes I did

**Comment by TBNRDev** [comment]
Duplicate of #6
