### ISSUE TITLE
Swiping up or tapping on more videos doesn't work

### ISSUE THREAD

**Issue by NAMA12345** [MaVeN-LLC/RVX#8]
As the title says swiping up or tapping on more videos doesn't work. So while watching a video you can't swipe or tap to choose suggested videos or subscribe to a channel quickly without exiting fullscreen.

**Comment by TBNRDev** [comment]
Fixed:)
https://github.com/MaVeN-LLC/RVX/releases/tag/v19.21.40

**Comment by NAMA12345** [comment]
Thanks
