### ISSUE TITLE
Feature Request: already seen

### ISSUE THREAD

**Issue by the1trubilly** [MaVeN-LLC/RVX#9]
It'd be cool to have a button similar to not interested, but just for stuff we've already seen. I don't want the algorithm thinking I don't like the video necessarily, I just don't wanna watch it again and want new recommendations.

**Comment by TBNRDev** [comment]
This isn't possible and should be reported to YouTube 


Latest version:
https://github.com/MaVeN-LLC/RVX/releases/tag/v19.21.40

**Comment by the1trubilly** [comment]
Thanks for letting me know
